Repository http-party/http-server, pull requests merged in 2019-04, with the labels that each got.

#326 Aggressively turn off caching when cache time set to -1
  lib/http-server.js
Labels: feature:http, next-minor

#485 Updated dependencies to fix security issues
  package-lock.json
  package.json
Labels: next-major

#477 Handle proxy errors
  lib/http-server.js
Labels: next-minor
