Repository http-party/http-server, pull requests merged in 2019-12, with the labels that each got.

#571 Add TLS/SSL usage description
  README.md
Labels: feature:documentation, patch

#577 Add CLI --version parameter
  bin/http-server
Labels: patch

#536 Send Accept-Ranges: bytes with every response
  lib/http-server.js
Labels: feature:http, major
